Deck overhaul
TanayB11/jadeocr-next pull request #21
Opened 2020-12-01 03:29 UTC by wizard1238

adds srs

2020-12-01 04:00 UTC, TanayB11 requested changes
The main thing is to extract functions in deckController where feasible. I'd prefer to use promise-based callbacks for async database calls or large search operations, but some other method that's nicer to read works too. If you want to change this at some other point, let me know.

2020-12-01 04:00 UTC, TanayB11 commented on server/src/controllers/classController.ts
> +    let saveClassAndDeck = function(classToSave, deckToSave) {
Better to use a callback.

2020-12-01 04:00 UTC, TanayB11 commented on server/src/controllers/classController.ts
> +        if (Class.assignedDecks.length == 0) {
Adopt a convention: `if (!Class.assignedDecks.length)` is better

2020-12-01 04:00 UTC, TanayB11 commented on server/src/controllers/classController.ts
> +    let saveClassAndDeck = function(classToSave, deckToSave) {
Why duplicate? Remove.

2020-12-01 04:00 UTC, TanayB11 commented on server/src/models/deckModel.ts
> +    access: {
I like this

2020-12-01 04:00 UTC, TanayB11 commented on server/src/models/userDetailedModel.ts
> +        totalQuizAttempts: Number,
Can combine `totalQuizAttempts` and the `quizAttempts` into an object.

2020-12-01 04:00 UTC, TanayB11 commented on server/src/models/userDetailedModel.ts
> +        totalQuizAttempts: Number,
One key is totalQuizAttempts, the other is quizAttempts

2020-12-01 04:00 UTC, TanayB11 commented on server/src/controllers/deckController.ts
> +            req.status(400).send('There was an error')
Might want to be more specific with this if you think we might hit this err

2020-12-01 04:00 UTC, TanayB11 commented on server/src/controllers/deckController.ts
> +        } else if (!returnedUser) {
Style...checking falsy value is better than checking `==null`

2020-12-01 04:00 UTC, TanayB11 commented on server/src/controllers/deckController.ts
> +                    req.status(400).send('There was an error')
Ditto from above

2020-12-01 04:00 UTC, TanayB11 commented on server/src/controllers/deckController.ts
> +exports.deck = function(req, res, next) {
Extract functions here...this definitely needs to be refactored

2020-12-01 04:00 UTC, TanayB11 commented on server/src/controllers/deckController.ts
> +exports.deck = function(req, res, next) {
Functions should do only one thing, so if your block of code is doing a different thing extract -> function

2020-12-01 04:00 UTC, TanayB11 commented on server/src/controllers/deckController.ts
> +            if (parseInt(i) == 14) break
Add a comment: Max per review session is 15
Or hardcode a constant `MAX_REVIEW_CARDS = 15`

2020-12-01 04:00 UTC, TanayB11 commented on server/src/controllers/deckController.ts
> +    let sendWithoutSRS = function(deck) {
Definte the functions outside and then put into exports

2020-12-01 04:00 UTC, TanayB11 commented on server/src/controllers/deckController.ts
> +    let sendWithoutSRS = function(deck) {
This is pretty hard to read...refactor for readability...I don't blame you, this part is pretty complex.

2020-12-01 04:00 UTC, TanayB11 commented on server/src/controllers/deckController.ts
> +            deckModel.findOne({_id: deckId}, function(deckErr, returnedDeck) {
Nested database calls 🙅🏽 , extract f u n c t i o n s

2020-12-01 04:00 UTC, TanayB11 commented on server/src/controllers/deckController.ts
> +                    checkAccess(returnedUser, returnedDeck, function(result, user, deck) {
The code would be much more readable if we had callbacks

2020-12-01 04:00 UTC, TanayB11 commented on server/src/controllers/deckController.ts
> +exports.practiced = function(req, res, next) {
extract functions :)

2020-12-01 04:00 UTC, TanayB11 commented on server/src/controllers/deckController.ts
> +exports.practiced = function(req, res, next) {
all of them in here

2020-12-01 04:00 UTC, TanayB11 commented on server/src/controllers/deckController.ts
> +exports.deck = function(req, res, next) {
Even if you use it just once, extracting makes the module as a whole more readable

2020-12-01 04:29 UTC, wizard1238 commented on server/src/controllers/classController.ts
> +        if (Class.assignedDecks.length == 0) {
The convention is what is seen in the code. I vaguely remember there being edge cases that didn't work if I do it the way you say. Idk tho.

2020-12-01 04:29 UTC, wizard1238 commented on server/src/controllers/classController.ts
> +    let saveClassAndDeck = function(classToSave, deckToSave) {
would have to pass in more objects. ig ill change this tho

2020-12-01 04:30 UTC, wizard1238 commented on server/src/controllers/deckController.ts
> +            req.status(400).send('There was an error')
This console logs the error. Most often going to be a connection error or smth like that so not anything user can do, console log prob enough?

2020-12-01 04:31 UTC, wizard1238 commented on server/src/controllers/deckController.ts
> +        } else if (!returnedUser) {
so isnt this wjhat you want?

2020-12-01 04:32 UTC, wizard1238 commented on server/src/controllers/deckController.ts
> +            deckModel.findOne({_id: deckId}, function(deckErr, returnedDeck) {
no point, this is still in error checking stages. the actual work is extracted into functions.

2020-12-01 04:32 UTC, wizard1238 commented on server/src/controllers/deckController.ts
> +                    checkAccess(returnedUser, returnedDeck, function(result, user, deck) {
opinions lol

2020-12-01 04:33 UTC, wizard1238 commented on server/src/models/deckModel.ts
> +    access: {
ty

2020-12-01 04:33 UTC, wizard1238 commented on server/src/models/userDetailedModel.ts
> +        totalQuizAttempts: Number,
would look more messy since we only have two things. will change if expand

2020-12-02 23:55 UTC, TanayB11 commented on server/src/controllers/classController.ts
> +        if (Class.assignedDecks.length == 0) {
Can you check? If there are edge cases to cover than this should be fine but I can't imagine there being any.

2020-12-02 23:55 UTC, TanayB11 commented on server/src/models/deckModel.ts
> +    access: {
You're welcome :)

2020-12-02 23:56 UTC, TanayB11 commented on server/src/models/userDetailedModel.ts
> +        totalQuizAttempts: Number,
We discussed this, I'm ok with that.

2020-12-02 23:57 UTC, TanayB11 commented on server/src/controllers/deckController.ts
> +            deckModel.findOne({_id: deckId}, function(deckErr, returnedDeck) {
Having database calls this deep is still pretty complex, and it'd be better to abstract this away inside the else block

2020-12-02 23:57 UTC, TanayB11 commented on server/src/controllers/deckController.ts
> +                    checkAccess(returnedUser, returnedDeck, function(result, user, deck) {
I'm a fan of promises, what can I say 🤷🏽‍♂️

2020-12-09 16:24 UTC, TanayB11 approved these changes

2020-12-09 16:24 UTC, merged